"use client";

import { ArrowLeft, Camera, Maximize, Smartphone } from "lucide-react";
import Link from "next/link";
import QRCode from "qrcode";
import { useCallback, useEffect, useState } from "react";
import { brand } from "@/brand";
import { BrandLogo } from "@/components/brand-logo";
import { ErrorState, Skeleton } from "@/components/ui/feedback";
import { getBrowserApi } from "@/lib/api/browser";
import { errorMessage } from "@/lib/format";

interface CurrentCode {
  svg: string;
  expiresAt: number;
}

/**
 * The QR parents scan to check in. It encodes a link to /check-in with this
 * minute's code, so the phone's own camera app works as well as the in-app
 * scanner. A new code is fetched the moment the current one is replaced.
 */
export function CheckInQrScreen() {
  const [current, setCurrent] = useState<CurrentCode | null>(null);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [now, setNow] = useState(() => Date.now());

  const refresh = useCallback(async () => {
    try {
      const { code, expiresAt } = await getBrowserApi().queue.getCheckInQrCode();
      const link = `${window.location.origin}/check-in?code=${code}`;
      const svg = await QRCode.toString(link, {
        type: "svg",
        errorCorrectionLevel: "M",
        margin: 1,
        color: { dark: "#1a1917", light: "#ffffff" },
      });
      setCurrent({ svg, expiresAt: new Date(expiresAt).getTime() });
      setLoadError(null);
    } catch (caught) {
      setLoadError(errorMessage(caught));
    }
  }, []);

  // First code, then a new one as each expires (and a retry if a fetch failed).
  useEffect(() => {
    const delay = current ? Math.max(current.expiresAt - Date.now(), 0) + 300 : loadError ? 5000 : 0;
    const timer = setTimeout(() => void refresh(), delay);
    return () => clearTimeout(timer);
  }, [current, loadError, refresh]);

  // The countdown.
  useEffect(() => {
    const timer = setInterval(() => setNow(Date.now()), 1000);
    return () => clearInterval(timer);
  }, []);

  // A reception tablet shouldn't dim and lock while showing the code.
  useEffect(() => {
    let lock: { release(): Promise<void> } | null = null;
    const request = () => {
      const wakeLock = (navigator as Navigator & {
        wakeLock?: { request(type: "screen"): Promise<{ release(): Promise<void> }> };
      }).wakeLock;
      void wakeLock
        ?.request("screen")
        .then((granted) => {
          lock = granted;
        })
        .catch(() => undefined);
    };
    request();
    // The lock is dropped when the tab is hidden; take it again on return.
    const onVisible = () => document.visibilityState === "visible" && request();
    document.addEventListener("visibilitychange", onVisible);
    return () => {
      document.removeEventListener("visibilitychange", onVisible);
      void lock?.release().catch(() => undefined);
    };
  }, []);

  const secondsLeft = current ? Math.max(0, Math.ceil((current.expiresAt - now) / 1000)) : 0;

  return (
    <div className="flex min-h-dvh flex-1 flex-col bg-surface-sunken">
      <header className="flex items-center justify-between gap-2 px-4 pt-[calc(1rem+env(safe-area-inset-top))]">
        <Link
          href="/admin"
          aria-label="Back to the staff terminal"
          className="flex size-12 items-center justify-center rounded-full text-foreground-muted hover:bg-surface-raised"
        >
          <ArrowLeft className="size-5" />
        </Link>
        <button
          type="button"
          onClick={() => void document.documentElement.requestFullscreen?.().catch(() => undefined)}
          className="flex min-h-12 items-center gap-2 rounded-full px-4 text-sm font-semibold text-foreground-muted hover:bg-surface-raised"
        >
          <Maximize aria-hidden className="size-4" />
          Full screen
        </button>
      </header>

      <main className="mx-auto flex w-full max-w-xl flex-1 flex-col items-center justify-center gap-6 px-6 pb-10 text-center">
        <div className="flex items-center gap-3">
          <BrandLogo className="size-12" />
          <p className="font-display text-xl font-bold text-foreground">{brand.name}</p>
        </div>

        <h1 className="font-display text-4xl font-extrabold tracking-tight text-foreground sm:text-5xl">
          Scan to check in
        </h1>

        <div className="w-full max-w-sm rounded-xl bg-neutral-0 p-5 shadow-lg ring-1 ring-border">
          {loadError && !current ? (
            <ErrorState message={loadError} onRetry={() => void refresh()} />
          ) : current ? (
            <div
              role="img"
              aria-label="Check-in QR code"
              className="aspect-square w-full [&>svg]:size-full"
              // SVG markup generated by the qrcode library from our own link.
              dangerouslySetInnerHTML={{ __html: current.svg }}
            />
          ) : (
            <Skeleton className="aspect-square w-full" />
          )}
        </div>

        <div className="flex w-full max-w-sm flex-col gap-2">
          <div
            aria-hidden
            className="h-1.5 w-full overflow-hidden rounded-full bg-border"
          >
            <div
              className="h-full rounded-full bg-primary-600 transition-[width] duration-1000 ease-linear"
              style={{ width: `${(secondsLeft / 60) * 100}%` }}
            />
          </div>
          <p className="text-sm text-foreground-muted tabular-nums" aria-live="off">
            {current ? `New code in 0:${String(secondsLeft).padStart(2, "0")}` : "Getting the code…"}
          </p>
        </div>

        <ol className="flex w-full max-w-md flex-col gap-3 text-left">
          <li className="flex items-center gap-3 rounded-lg bg-surface-raised px-4 py-3 text-foreground">
            <Smartphone aria-hidden className="size-5 shrink-0 text-primary-600" />
            <span>
              Open <strong>{brand.name}</strong> on your phone and tap <strong>Check in</strong>.
            </span>
          </li>
          <li className="flex items-center gap-3 rounded-lg bg-surface-raised px-4 py-3 text-foreground">
            <Camera aria-hidden className="size-5 shrink-0 text-primary-600" />
            <span>Point the camera at this code. The phone&apos;s camera app works too.</span>
          </li>
        </ol>
      </main>
    </div>
  );
}
